# Generated by Django 5.2.9 on 2026-02-22 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta_app', '0002_alter_comment_id_alter_commentlike_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='hashtag',
            field=models.ManyToManyField(blank=True, to='insta_app.hashtag'),
        ),
    ]
