# Generated by Django 5.2.9 on 2026-02-23 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insta_app', '0003_alter_post_hashtag'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='commentlike',
            unique_together={('user', 'comment')},
        ),
        migrations.AlterUniqueTogether(
            name='postlike',
            unique_together={('user', 'post')},
        ),
    ]
