# Generated by Django 5.2.9 on 2026-02-25 18:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta_app', '0006_userprofile_phone_number_alter_hashtag_hashtag_name_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='postlike',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='phone_number',
        ),
        migrations.AlterField(
            model_name='hashtag',
            name='hashtag_name',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='location',
            name='location_name',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='postlike',
            name='like',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='postlike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like', to=settings.AUTH_USER_MODEL),
        ),
    ]
